### ISSUE TITLE
autodoc fails when config file is present

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/ewatercycle#169]
I tried to run `cd docs && make html`with a `~/.config/ewatercycle/ewatercycle.yaml` config file present. 
It failed to run autodoc with following exception:
```python
WARNING: autodoc: failed to import module 'ewatercycle'; the following exception was raised:
Traceback (most recent call last):
  File "/home/verhoes/miniconda39/envs/ewatercycle/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 70, in import_module
    return importlib.import_module(modname)
  File "/home/verhoes/miniconda39/envs/ewatercycle/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/verhoes/git/eWaterCycle/ewatercycle/ewatercycle/__init__.py", line 1, in <module>
    from .config import CFG
  File "/home/verhoes/git/eWaterCycle/ewatercycle/ewatercycle/config/__init__.py", line 84, in <module>
    from ._config_object import CFG, Config, SYSTEM_CONFIG, USER_HOME_CONFIG, DEFAULT_CONFIG
  File "/home/verhoes/git/eWaterCycle/ewatercycle/ewatercycle/config/_config_object.py", line 159, in <module>
    CFG = Config._load_user_config(USER_CONFIG)
  File "/home/verhoes/git/eWaterCycle/ewatercycle/ewatercycle/config/_config_object.py", line 41, in _load_user_config
    mapping['ewatercycle_config'] = filename
TypeError: 'load' object does not support item assignment
```
Causing all the API reference pages to be empty.

When I run normal ipython shell the CFG loads correctly
```pycon
In [1]: from ewatercycle import CFG
In [2]: CFG
Out[2]: 
Config({'container_engine': 'docker',
        'esmvaltool_config': None,
        'ewatercycle_config': PosixPath('/home/verhoes/.config/ewatercycle/ewatercycle.yaml'),
        'grdc_location': PosixPath('/home/verhoes/git/eWaterCycle/ewatercycle/docs/examples/grdc'),
        'output_dir': PosixPath('/home/verhoes/git/eWaterCycle/ewatercycle/docs/examples/output'),
        'parameter_sets': {'lisflood_fraser': {'config': 'lisflood_fraser/settings_lat_lon-Run.xml',
                                               'directory': 'lisflood_fraser',
                                               'doi': 'N/A',
                                               'supported_model_versions': {'20.10'},
                                               'target_model': 'lisflood'},
                           'pcrglobwb_example_case': {'config': 'pcrglobwb_example_case/setup_natural_test.ini',
                                                      'directory': 'pcrglobwb_example_case',
                                                      'doi': 'N/A',
                                                      'supported_model_versions': {'setters'},
                                                      'target_model': 'pcrglobwb'},
                           'wflow_rhine_sbm_nc': {'config': 'wflow_rhine_sbm_nc/wflow_sbm_NC.ini',
                                                  'directory': 'wflow_rhine_sbm_nc',
                                                  'doi': 'N/A',
                                                  'supported_model_versions': {'2020.1.1'},
                                                  'target_model': 'wflow'}},
        'parameterset_dir': PosixPath('/home/verhoes/git/eWaterCycle/ewatercycle/docs/examples/parameter-sets'),
        'singularity_dir': None})
```

If I remove  `~/.config/ewatercycle/ewatercycle.yaml` the `make html` works as expected.

**Comment by sverhoeven** [comment]
No problem on readthedocs.org as build there is missing config file.

**Comment by sverhoeven** [comment]
We could switch to https://pypi.org/project/sphinx-autoapi/ instead of calling apidoc cli in docs/conf.py

**Comment by sverhoeven** [comment]
The problem arises because apidoc does actual imports and our imports executes code (load config file) while all 3rd party imports are being mocked.

**Comment by Peter9192** [comment]
Does sphinx-autoapi solve that problem?

**Comment by sverhoeven** [comment]
sphinx-autoapi does not perform imports (aka executes code) instead it parses files so yes.

**Comment by Peter9192** [comment]
Sounds like a much better solution for us! If it's not too much work, we can do it 👍

**Comment by sverhoeven** [comment]
The docstring of ewatercycle.forcing.load_foreign and ewatercycle.forcing.generate get made by doing the imports and executing code at https://github.com/eWaterCycle/ewatercycle/blob/5dbfee96125eefd06a488b095f9134fc49d36f5b/ewatercycle/forcing/__init__.py#L160-L164 . Switching to sphinx-autoapi will probably break that.

**Comment by Peter9192** [comment]
Perhaps we can stop mocking imports but actually build the package with conda?
