### ISSUE TITLE
set_value() and set_value_at_coords() not working for wflow 

### ISSUE THREAD

**Issue by pauwiersma** [eWaterCycle/ewatercycle#270]
I tried to set snow values for wflow 2020.1.2 (ewatercycle 1.1.3) but I got the following errors:
```
snow = model.get_value_as_xarray("Snow")
snow_array = np.array(snow.data,dtype=np.float64)
model.set_value('Snow',snow_array)
#(or model.set_value('Snow',snow_array.flatten()))
---------------------------------------------------------------------------
_InactiveRpcError                         Traceback (most recent call last)
/tmp/ipykernel_128173/910044003.py in <module>
      6 
      7 #model.set_value_at_indices('Snow',[0,0],[0,1],np.array([10,10])) # Doesn't exist
----> 8 model.set_value('Snow',snow_array) #Error:Input must be 2D np array"

~/anaconda3/envs/ewatercycle/lib/python3.9/site-packages/ewatercycle/models/abstract.py in set_value(self, name, value)
    123 
    124         """
--> 125         self.bmi.set_value(name, value)
    126 
    127     def set_value_at_coords(

~/anaconda3/envs/ewatercycle/lib/python3.9/site-packages/grpc4bmi/bmi_grpc_client.py in set_value(self, var_name, src)
    173         else:
    174             raise NotImplementedError("Arrays with type %s cannot be transmitted through this GRPC channel" % src.dtype)
--> 175         self.stub.setValue(request)
    176 
    177     def set_value_at_indices(self, var_name, indices, src):

~/anaconda3/envs/ewatercycle/lib/python3.9/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    944         state, call, = self._blocking(request, timeout, metadata, credentials,
    945                                       wait_for_ready, compression)
--> 946         return _end_unary_response_blocking(state, call, False, None)
    947 
    948     def with_call(self,

~/anaconda3/envs/ewatercycle/lib/python3.9/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    847             return state.response
    848     else:
--> 849         raise _InactiveRpcError(state)
    850 
    851 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: Input must be two-dimensional NumPy array"
	debug_error_string = "{"created":"@1637228265.079998264","description":"Error received from peer ipv6:[::1]:39511","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Exception calling application: Input must be two-dimensional NumPy array","grpc_status":2}"
>
```

```
snow = model.get_value_as_xarray("Snow")
snow_array = np.array(snow.data,dtype=np.float64)
model.set_value_at_coords('Snow',[47.15,47.16],[8.688,8.688],np.array([10,10])) 
---------------------------------------------------------------------------
_InactiveRpcError                         Traceback (most recent call last)
/tmp/ipykernel_128173/1402431263.py in <module>
      2 snow_array = np.array(snow.data,dtype=np.float64)
      3 
----> 4 model.set_value_at_coords('Snow',[47.15,47.16],[8.688,8.688],np.array([10,10]))
      5 #Error: set_value_at_indices() got an unexpected keyword argument 'indices'
      6 

~/anaconda3/envs/ewatercycle/lib/python3.9/site-packages/ewatercycle/models/abstract.py in set_value_at_coords(self, name, lat, lon, values)
    139         indices = self._coords_to_indices(name, lat, lon)
    140         indices = np.array(indices)
--> 141         self.bmi.set_value_at_indices(name, indices, values)
    142 
    143     def _coords_to_indices(

~/anaconda3/envs/ewatercycle/lib/python3.9/site-packages/grpc4bmi/bmi_grpc_client.py in set_value_at_indices(self, var_name, indices, src)
    193         else:
    194             raise NotImplementedError("Arrays with type %s cannot be transmitted through this GRPC channel" % src.dtype)
--> 195         self.stub.setValueAtIndices(request)
    196 
    197     def get_grid_size(self, grid_id):

~/anaconda3/envs/ewatercycle/lib/python3.9/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    944         state, call, = self._blocking(request, timeout, metadata, credentials,
    945                                       wait_for_ready, compression)
--> 946         return _end_unary_response_blocking(state, call, False, None)
    947 
    948     def with_call(self,

~/anaconda3/envs/ewatercycle/lib/python3.9/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    847             return state.response
    848     else:
--> 849         raise _InactiveRpcError(state)
    850 
    851 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: set_value_at_indices() got an unexpected keyword argument 'indices'"
	debug_error_string = "{"created":"@1637228158.657787507","description":"Error received from peer ipv6:[::1]:39511","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Exception calling application: set_value_at_indices() got an unexpected keyword argument 'indices'","grpc_status":2}"
>
```
They both seem to be bugs, since in set_value() I specifically use a 2D numpy array as input and set_value_at_indices() in bmi_grpc_client.py has an argument called 'indices'.
 Flattening the input array of set_value() apparently works in [this example notebook ](https://github.com/eWaterCycle/technicalPaperExampleNotebooks/blob/main/Case4_ForcePCRGlobWBWithadditionalEvapInfo.ipynb), but it wasn't the case for me, possibly because I run wflow and the example notebook runs PCR-GLOB.

**Comment by Peter9192** [comment]
I spent some time looking at this. I can reproduce the problem, but I still don't have any clues as to where the problem originates. Perhaps mismatching BMI versions? @sverhoeven any ideas?

**Comment by sverhoeven** [comment]
## For set_value 

The wflow code expects a 2d array and grpc4bmi expects a 1d array. 

The wflow code should be adjusted at https://github.com/eWaterCycle/wflow/blob/docker-fixes-2020.1.2/wflow/wflow_bmi.py#L1367 so the `src` variable gets reshaped from 1d to 2d. Similar to [Pcrglobwb](https://github.com/eWaterCycle/PCR-GLOBWB_model/blob/bmi_fixes_setters/model/bmiPcrglobwb.py#L500) 


## For set_value_at_indices

The grpc4bmi server is calling the wflow code at https://github.com/eWaterCycle/grpc4bmi/blob/0.2.x/grpc4bmi/bmi_grpc_server.py#L128 with a named `indices` argument.
While at https://github.com/eWaterCycle/wflow/blob/docker-fixes-2020.1.2/wflow/wflow_bmi.py#L1149 it is named `inds`.
I think renaming `inds` argument to `indices` should solve it.

We should make a `docker-fixes-2020.1.3` branch, make those changes and make new Docker/singularity images.

**Comment by Peter9192** [comment]
Thanks for investigating @sverhoeven!! So for my understanding, the errors originate from wflow itself, and are passed on to the user through grpc4bmi?

**Comment by sverhoeven** [comment]
Yep, `Input must be two-dimensional NumPy array` is the exception message raised in the wflow code.

I was able to reproduce with Docker and without grpc4bmi
```shell
docker run -ti --rm --entrypoint /opt/conda/envs/wflow/bin/python ewatercycle/wflow-grpc4bmi:2020.1.2
```
```python
from wflow.wflow_bmi import wflowbmi_csdms
model = wflowbmi_csdms()
model.initialize('/opt/wflow/examples/wflow_rhine_sbm/wflow_sbm.ini')
model.update()
v = model.get_value('Snow')
>>> v.shape
(169, 187)
model.set_value('Snow', v)
# works because wflow code expects 2d array and grpc4bmi does a flatten.
>>> model.set_value('Snow', v.flatten())
2022-01-12 14:21:14,905 - wflow_sbm.ini - wf_DynamicFramework - ERROR -   File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/wflow/lib/python3.9/site-packages/wflow-2020.1.2.dev37+gd9ee174b-py3.9.egg/wflow/wflow_bmi.py", line 1467, in set_value
    self.dynModel.wf_setValuesAsNumpy(long_var_name, src)
  File "/opt/conda/envs/wflow/lib/python3.9/site-packages/wflow-2020.1.2.dev37+gd9ee174b-py3.9.egg/wflow/wf_DynamicFramework.py", line 2197, in wf_setValuesAsNumpy
    arpcr = pcr.numpy2pcr(pcr.Scalar, np.flipud(values).copy(), -999)
  File "/opt/conda/envs/wflow/lib/python3.9/site-packages/pcraster/numpy_operations.py", line 34, in numpy2pcr
    return _pcraster.numpy2pcr(_pcraster.clone(), dataType, array, mv)

2022-01-12 14:21:14,905 - wflow_sbm.ini - wf_DynamicFramework - ERROR - <class 'ValueError'>: Input must be two-dimensional NumPy array
```
So I get same error that is reported.

**Comment by sverhoeven** [comment]
Do we want to replace `ewatercycle/wflow-grpc4bmi:2020.1.2` with the changes or create a `2020.1.3` version?

Steps to create and publish 2020.1.3 image.
* [x] Create https://github.com/eWaterCycle/wflow/tree/docker-fixes-2020.1.3 branch 
* [x] Create and push `ewatercycle/wflow:2020.1.3` Docker image to Docker Hub
* [ ] Create new version of eWaterCycle Python package with wflow `2020.1.3 ` version, see https://ewatercycle.readthedocs.io/en/latest/adding_models.html#adding-a-new-version-of-a-model
  * [x] `docker push ewatercycle/wflow-grpc4bmi:2020.1.3`
  * [x] ewatercycle-wflow-grpc4bmi_2020.1.3.sif on dcache

**Comment by pauwiersma** [comment]
Indeed thanks for helping out @sverhoeven ! The errors make sense now, I'm glad you could fix it. 
I just pulled the 2020.1.3 docker image, made the necessary adjustments in the package and tried it out and it works perfectly. 
Thanks also to @Peter9192 for your time and help. Should I close the issue or leave it open for now?

**Comment by sverhoeven** [comment]
Thanks for testing 

[1.1.4](https://github.com/eWaterCycle/ewatercycle/releases/tag/1.1.4) has been released with the new wflow version.
